#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e # Exit on any error



echo "Formatting code..."
npm run format

echo "Checking formatting..."
npm run format:check

echo "Pre-commit checks passed."
